field: 71730b1a-49d4-4e53-8f27-408897679aeb # Matrix Field
fieldLayouts:
  9a3ddfa0-4f0e-4ff1-92e7-8149105b28cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c100d296-028a-42e6-bfc7-77ff15eeae9a # Field One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27fee96e-fa12-4594-9c8b-178930589f2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 019d883f-364d-43a7-b347-86c72d16f5e6 # Field Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12f349e1-eee3-4af1-9621-5abe1c113a27
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66612de3-3430-4334-9905-de4f45c84eba
        userCondition: null
fields:
  019d883f-364d-43a7-b347-86c72d16f5e6: # Field Two
    columnSuffix: xkdaqntt
    contentColumnType: text
    fieldGroup: null
    handle: fieldTwo
    instructions: null
    name: 'Field Two'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c100d296-028a-42e6-bfc7-77ff15eeae9a: # Field One
    columnSuffix: vpcruclj
    contentColumnType: text
    fieldGroup: null
    handle: fieldOne
    instructions: null
    name: 'Field One'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockTypeOne
name: 'Block Type One'
sortOrder: 1
