name: Build Docs

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Generate docs
        run: |
          cat vendor/markhuot/craft-pest-core/src/bin/generate-docs.php
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/factories/Factory.php docs/factories.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/factories/Entry.php docs/factories/entry.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/factories/Asset.php docs/factories/asset.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/dom/NodeList.php docs/dom/node-list.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/dom/Form.php docs/dom/forms.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/behaviors/TestableResponseBehavior.php docs/assertions/response.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/behaviors/TestableElementBehavior.php docs/assertions/element.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/test/DatabaseAssertions.php docs/assertions/database.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/test/RequestBuilders.php docs/making-requests.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/web/BenchmarkResult.php docs/assertions/benchmark.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/test/CookieState.php docs/cookies.md
          php vendor/markhuot/craft-pest-core/src/bin/generate-docs.php src/test/ActingAs.php docs/logging-in.md

      - name: Add files
        run: git add -A docs/

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_email: docbot@markhuot.com
          commit_user_name: docbot
          commit_message: GitHub action updating docs
